name: End-to-end tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Start server
        run: pnpm dev &

      - name: Install browsers
        run: pnpm playwright install

      - name: Run tests
        run: pnpm test
