name: End-to-end tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run yarn install
        run: yarn install

      - name: Start server
        run: yarn run dev &

      - name: Install browsers
        run: yarn playwright install

      - name: Run tests
        run: yarn test
