name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: corepack enable
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Show node version
      run: node -v
    - name: Get pnpm store directory path
      id: pnpm-store-dir-path
      run: echo "::set-output name=dir::$(pnpm store path)"
    - uses: actions/cache@v3
      id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.pnpm-store-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install dependencies
      run: pnpm install
    - name: Run prettier
      run: pnpm pretty-check
